storage:
  history_db_path: ../data/conversation_history.db

llm:
  model: "Pro/Qwen/Qwen2-7B-Instruct"
  base_url: "https://api.siliconflow.cn/v1/chat/completions"
  api_key: sk-bhbgvzuyrhcnmqzobtjdrahvdijaaorhqqomqlslsllpynpj
